spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  profiles:
    active: local
  main:
    banner-mode: log
  security:
    oauth2:
      client:
        registration:
          jwt:
            client-id: ${JWT_CLIENT_ID}
            client-secret: ${JWT_CLIENT_SECRET}
            client-authentication-method: client-secret-post
            authorization-grant-type: client-credentials
            provider: jwt
        provider:
          jwt:
            token-uri: ${JWT_TOKEN_URI}
moauthoriser:
  enabled: true
  jdbc:
    url: ${MEMBER_API_DB}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8080
  servlet:
    context-path: /readvantage
  error:
    include-message: always
    include-stacktrace: on-param
    include-binding-errors: always

app:
  cors:
    allowed-origins: http://localhost:5173

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{requestId}] [%X{userId}] - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{requestId}] [%X{userId}] - %msg%n"

management:
  endpoint:
    health:
      show-details: always
