spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  profiles:
    active: local
  main:
    banner-mode: log



server:
  port: 8080
  servlet:
    context-path: /readvantage
  error:
    include-message: always
    include-stacktrace: on-param
    include-binding-errors: always

app:
  cors:
    allowed-origins: http://localhost:5173

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{requestId}] [%X{userId}] - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{requestId}] [%X{userId}] - %msg%n"

management:
  endpoint:
    health:
      show-details: always
